### ISSUE TITLE
Shuffle install causes crash

### ISSUE THREAD

**Issue by catfatwm** [astronautlevel2/Anemone3DS#205]
On the last few versions if i try to shuffle install on my o2ds I get a crash. Ive tried to install older versions and it seems to also cause a crash when I shuffle install. Is there a discord community around this app?

Yea I should have mentioned old 2ds luma 9.1 latest 3ds update and I should Also mention 128gb. Sd card, random I know but its caused weird problems in the past.

**Comment by catfatwm** [comment]
![15590830730463302422553875750408](https://user-images.githubusercontent.com/29764430/58516962-59d51300-816f-11e9-9c31-779adb0f2a4e.jpg)
Its more widespread then I thought before. I can replicate this by lraving the app open or by scanni g a qr code or by switching from themes to splashes or possibly even breathing apparently.

**Comment by Volkaru** [comment]
Also getting this issue on a New3DS XL Running 11.10 with Luma 9.1. Any time I try to shuffle install more than four themes, it crashes. And it seems that even without those themes causing a crash, it doesn't properly activate a shuffle. Instead sticking to just the first theme on the shuffle list.

**Comment by Helloman892** [comment]
Which versions are you both using?

**Comment by Sophie-bear** [comment]
This happens to me as well. Version 2.0.1.

**Comment by catfatwm** [comment]
> Which versions are you both using?

Its weird I remember a time when this worked perfectly, but the last 5 or 6 versions released, all cause crashes on shuffle install. I wonder if ot has to do with me switching to 128gb sd card, as that's the only thing thats changed for me in the last few years.

**Comment by NuttySian** [comment]
> Its weird I remember a time when this worked perfectly, but the last 5 or 6 versions released, all cause crashes on shuffle install. I wonder if ot has to do with me switching to 128gb sd card, as that's the only thing thats changed for me in the last few years.

I think it might be as I've just done the same and I'm having the same issue, but my other 3ds only has 16gb and shuffle themes work fine.

**Comment by 4maself** [comment]
I've been experiencing the same crash on my New 3DSXL (sys 11.10.0-43E) Anemone version v2.0.1 and Luma v10.0.1 with 8GB SD. Odd thing is that it only happens when I leave sound on. When I queue everything with sound off, it won't crash. 
When I select everything in series (e.g. from 1 to 7 in my case), however it won't actually work (It will only display the first selected theme). 
When I queued everything in random order it works as expected.

**Comment by ktweed** [comment]
I also get a crash on N3DS XL with both 4 and 5 themes selected and a 32gb micro SD card, I haven't tried any others. I attached ARM11 crash dumps in ZIPs (GitHub won't allow uploading .dmp files), the first is 5 themes and the second is 4.
[crash_dump_00000001.zip](https://github.com/astronautlevel2/Anemone3DS/files/3491015/crash_dump_00000001.zip)
[crash_dump_00000002.zip](https://github.com/astronautlevel2/Anemone3DS/files/3491016/crash_dump_00000002.zip)

**Comment by Davixk** [comment]
I get this same error I'm on anemone 2.0.1, latest Luma and I also recently changed my SD card from 4gb to 64gb size

**Comment by RaikoKitame** [comment]
Hello everybody,

New 2DS XL
Firmware : 11.13.0-45E
CFW: Luma 10.1.3/ Boot9Strap 1.3
Anemone3DS- 2.0.1

I've got the same too...

Any idea?

**Comment by SleepyLark** [comment]
It still crashes on the latest version  (2.1.0) running on Luma3DS 10.1.3.
What I've noticed is it crashes whenever I try to install a new shuffle theme on a existing shuffle theme (both set on the max of 10) it crashes, but when I start it up the home menu is back to the default theme

**Comment by astronautlevel2** [comment]
Can you provide a crash dump file? When you get to the "An exception occurred" screen you can press A to save a file, can you post that file here? Thanks.

**Comment by SleepyLark** [comment]
[arm11.zip](https://github.com/astronautlevel2/Anemone3DS/files/4789585/arm11.zip)

**Comment by astronautlevel2** [comment]
Thanks! I'll get to work on it

**Comment by astronautlevel2** [comment]
This seems to actually be a separate issue from the one posted above, as the crash is in the fs process rather than in Anemone3DS.

Are you able to use gdb to get a backtrace? It would make debugging this significantly easier as I'm currently unable to replicate.

Also, have you tried a different SD card?

**Comment by mbc07** [comment]
I think it might be related to a memory leak somewhere. I noticed that if I preview a lot of themes by pressing Y (about 100 or more) before actually making the selection and performing the shuffle install, it's practically guaranteed that Anemone3DS will crash right after starting the shuffle install. If I just open Anemone3DS, select the themes I want on the list, without previewing any of them, then proceed with the shuffle install, it always works, no crashes.

I noticed this behavior with version 2.1.0 of Anemone3DS, on a New 3DS XL running on firmware 11.13-45U with Luma3DS 10.1.3, while using a 32 GB Class 4 microSD card. Unfortunately I didn't take any crash dump but I hope this tip helps narrowing down the actual issue...

**Comment by astronautlevel2** [comment]
@mbc07 If you could replicate the bug and save a crash dump that would be helpful

**Comment by mbc07** [comment]
Ok, [here is it](https://github.com/astronautlevel2/Anemone3DS/files/4800474/arm11.zip).

**Comment by astronautlevel2** [comment]
This seems to be the same crash as @SleepyLark. Could one of you upload your themes folder so I can attempt to replicate?

**Comment by astronautlevel2** [comment]
Asking again for either @mbc07 or @SleepyLark to upload your themes folder - I still can't replicate this bug and hope that a copy of the theme folder will help me in doing so. 

I think this is the last major bug and am hoping to get it solved as soon as possible but I need to be able to replicate it in order to do that.

**Comment by SleepyLark** [comment]
> Asking again for either @mbc07 or @SleepyLark to upload your themes folder - I still can't replicate this bug and hope that a copy of the theme folder will help me in doing so.
> 
> I think this is the last major bug and am hoping to get it solved as soon as possible but I need to be able to replicate it in order to do that.

Sorry, I've been busy.  I could upload it, but I have a lot of themes, like I think around 100.  Give me a couple hours and I'll send a link

**Comment by astronautlevel2** [comment]
No worries! Feel free to send it once it's uploaded, no big rush.

**Comment by timmy-tt** [comment]
I also have this issue. I'm not sure if I should be sharing this here due to the nature of the themes contained on it but my theme folder essentially have all themes from [this pack](https://archive.org/details/3DSThemesUSA1), each one unzipped on its own subfolder instead of having them as .ZIP files. 

I did this because Anemone3DS freezes for a little while on the "loading themes" screen when launching the app (probably due to the huge number of themes), having them unzipped seems to help with that, as it hangs for less time that way.

Apart from that, I'm experiencing exactly the same behavior @mbc07 described: if I preview a lot of themes before doing the shuffle install, it always crash. If I just open Anemone3DS and select the themes, without previewing any, shuffle install always succeed. BTW I'm using a 32 GB card too, if that's relevant...

**Comment by SleepyLark** [comment]
@astronautlevel2 [Here's my folder](https://drive.google.com/file/d/1dz6kt-BH6fiACOzlbB5xbaV_FqwMXecZ/view?usp=sharing)
Just a warning, it's about 1 GB, I'll remove the file probably by the end of the week or until you say so

**Comment by mbc07** [comment]
Sorry for the late reply, unfortunately the New 3DS where I experienced this issue was borrowed and it's not with me anymore, so I won't be able to help any further...

**Comment by astronautlevel2** [comment]
@SleepyLark I don't have access to the link you posted

**Comment by SleepyLark** [comment]
> @SleepyLark I don't have access to the link you posted

Oof, I'm sorry.  I keep forgetting that Google changed how the share button works.  I changed the permissions so it should work now

**Comment by astronautlevel2** [comment]
Can anyone in this thread experiencing this issue give this build a try?

https://user-images.githubusercontent.com/7305572/103041937-e1e6ee80-4545-11eb-88c1-3426c2155e8d.png

**Comment by astronautlevel2** [comment]
Closing this for now given there's no further information on this issue and I believe it should be solved in the latest release. Will re-open if it's still a problem.
