### ISSUE TITLE
'FS Error: Get new SD card' for themes with symbols in the name persisting

### ISSUE THREAD

**Issue by IcedMochaArt** [astronautlevel2/Anemone3DS#292]
**Description**
Even after updating to v2.3.1 I'm still experiencing the bug that gives FS Error: Get new SD Card when I try to download a theme with an asterisk in its name. In issue #267 the problem was an ampersand, I tried this and it does not give me an error. But like in issue #288 it still gives an error for asterisks.

**Steps to reproduce**
I attempted to download one of the DECO*27 themes by Siesta. Downloading these or any other with an asterisks in its name via QR code or via the in-app search function results in the same error.

**Expected behavior**
For a theme to be installed as usual.

**Screenshots**
![error](https://github.com/astronautlevel2/Anemone3DS/assets/135028062/ed0e17d2-e41f-4072-813d-c2312a487205)

**System information**
*System model* New 2DS XL

*System firmware version* 11.17.0-50E

*Anemone3DS version* v2.3.1

*Luma3DS version* v.12.0.1

**Comment by Zemogiter** [comment]
I have the same error. New 3DS XL, Anemone 2.3.1, Luma3DS 13.0.2

**Comment by Helloman892** [comment]
This should be as simple as updating the filter [here](https://github.com/astronautlevel2/Anemone3DS/blob/master/include/fs.h#L32), which I can do and PR soon. I'll link it back to this issue - feel free to ping me next week if I forget, and otherwise, I'll upload a build that should resolve the issue. I can't guarantee it'll make it to a full release any time soon, because there currently isn't much to put in there, but if enough people run into this I can push it out as a patch release.
