### ISSUE TITLE
Full German Translation

### ISSUE THREAD

**Issue by ZetaDesigns** [astronautlevel2/Anemone3DS#44]
I'm just leaving this here for future reference, when astronautlevel finished writing the Translationframework. I translated every string I could find to german.

[german.txt](https://github.com/astronautlevel2/Anemone3DS/files/1275396/german.txt)

**Comment by daedreth** [comment]
Would it not be better for the final user to actually translate "Splash", "Theme" and "Shuffle"?

**Comment by ZetaDesigns** [comment]
The german language is used to what we call "anglizismen", using english words in german sentences. So no, its fine how it is.

**Comment by daedreth** [comment]
I'm aware that Anglizismen are a large part of the german language, however to be frank having sentences like: "Installiere Shuffle Theme" barely even seem translated.
One might substitute "Theme" for "Motiv" or similar.

**Comment by ZetaDesigns** [comment]
Most german people I know just call it "Theme". "Motiv" sounds very out of place, dont you think?

**Comment by daedreth** [comment]
Suit yourself

**Comment by Kyusetzu** [comment]
Well, I'm just gonna leave this here.
I don't really think a full german translation would make sense at all. 
@ZetaDesigns Is right. Anglizismen are very important.
I just would stick to the Nintendo translations.
Make "Shuffle Theme" "zufälliges Design"
and let "Splash" be "Splash" since there isn't a fitting word.
You just could translate it into "Ladebildschirm" which means "Loading Screen"

**Comment by astronautlevel2** [comment]
Closed (#80)
