### ISSUE TITLE
Install themes without BGM

### ISSUE THREAD

**Issue by roryfree** [astronautlevel2/Anemone3DS#76]
Themely had the option to install themes without the music. Does Anemone3DS not have this feature, or am I just not seeing it? I've come across themes that I like visually, but also have music included that sounds quite frankly awful, so it would be nice to be able to do that.

**Comment by Helloman892** [comment]
It doesn't exist yet, but it is coming Soon™. What we do have in contrast is the ability to install *just* the BGM, so you can overwrite bad BGM with good BGM. It's a stop-gap measure, but it's what we've got for now.

**Comment by LiquidFenrir** [comment]
Not released, but implemented, so I'm closing this.

**Comment by DMSalesman** [comment]
@LiquidFenrir Hello there. May I ask whether there is any issue preventing the No BGM Installs from being released? As of now, that's the only thing that keeps me on Themely.

**Comment by DMSalesman** [comment]
@Helloman892 So, in other words, one could simply install Custom Theme over a stock Home Menu theme in order to get Custom Theme + Stock Theme BGM, is it? Handy.

I'm not sure whether this was mentioned over at the project's Wiki, though; you may want to check. Thanks for the fast response, and good luck with Anemone.
